// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\4\1\0"+
    "\1\5\2\0\1\6\2\0\2\7\2\6\1\7\1\6"+
    "\1\10\1\11\12\12\1\0\1\7\1\13\1\14\1\13"+
    "\2\0\4\15\1\16\14\15\1\17\10\15\4\0\1\15"+
    "\1\0\1\20\1\21\1\22\1\23\1\24\1\25\1\15"+
    "\1\26\1\27\1\15\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\15\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\15\1\7\1\0\1\7\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\4"+
    "\1\5\1\6\1\5\20\7\1\0\1\10\1\11\1\0"+
    "\7\7\1\12\3\7\1\13\12\7\1\14\12\7\1\15"+
    "\1\16\7\7\1\17\5\7\1\20\4\7\1\21\10\7"+
    "\1\22\3\7\1\23\1\24\1\25\2\7\1\26\6\7"+
    "\1\27\1\30\7\7\1\31\1\32\1\33\1\34\3\7"+
    "\1\35\1\36\1\37\3\7\1\40\1\7\1\41\1\7"+
    "\1\42\6\7\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\46\0\114\0\162\0\46\0\46"+
    "\0\230\0\276\0\344\0\u010a\0\u0130\0\u0156\0\u017c\0\u01a2"+
    "\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2"+
    "\0\u02f8\0\u031e\0\u0344\0\162\0\46\0\u036a\0\u0390\0\u03b6"+
    "\0\u03dc\0\u0402\0\u0428\0\u044e\0\u0474\0\u049a\0\u010a\0\u04c0"+
    "\0\u04e6\0\u050c\0\u010a\0\u0532\0\u0558\0\u057e\0\u05a4\0\u05ca"+
    "\0\u05f0\0\u0616\0\u063c\0\u0662\0\u0688\0\u0390\0\u06ae\0\u06d4"+
    "\0\u06fa\0\u0720\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de\0\u0804"+
    "\0\u010a\0\u010a\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8"+
    "\0\u090e\0\u010a\0\u0934\0\u095a\0\u0980\0\u09a6\0\u09cc\0\u010a"+
    "\0\u09f2\0\u0a18\0\u0a3e\0\u0a64\0\u010a\0\u0a8a\0\u0ab0\0\u0ad6"+
    "\0\u0afc\0\u0b22\0\u0b48\0\u0b6e\0\u0b94\0\u010a\0\u0bba\0\u0be0"+
    "\0\u0c06\0\u010a\0\u010a\0\u010a\0\u0c2c\0\u0c52\0\u0c78\0\u0c9e"+
    "\0\u0cc4\0\u0cea\0\u0d10\0\u0d36\0\u0d5c\0\u010a\0\u010a\0\u0d82"+
    "\0\u0da8\0\u0dce\0\u0df4\0\u0e1a\0\u0e40\0\u0e66\0\u010a\0\u010a"+
    "\0\u010a\0\u010a\0\u0e8c\0\u0eb2\0\u0ed8\0\u010a\0\u010a\0\u010a"+
    "\0\u0efe\0\u0f24\0\u0f4a\0\u010a\0\u0f70\0\u010a\0\u0f96\0\u010a"+
    "\0\u0fbc\0\u0fe2\0\u1008\0\u102e\0\u1054\0\u107a\0\u010a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\2\13\1\14\1\15\1\16\1\14\1\17"+
    "\1\20\1\21\1\22\1\23\1\14\1\24\3\14\1\25"+
    "\1\14\1\26\1\27\1\30\1\31\1\14\1\32\1\33"+
    "\2\14\47\0\2\3\1\0\1\3\41\0\5\34\1\35"+
    "\40\34\11\0\1\36\44\0\1\37\1\0\1\12\47\0"+
    "\1\7\43\0\1\14\2\0\31\14\12\0\1\14\2\0"+
    "\27\14\1\40\1\14\12\0\1\14\2\0\24\14\1\41"+
    "\4\14\12\0\1\14\2\0\21\14\1\42\7\14\12\0"+
    "\1\14\2\0\3\14\1\43\10\14\1\44\2\14\1\45"+
    "\11\14\12\0\1\14\2\0\7\14\1\46\7\14\1\47"+
    "\11\14\12\0\1\14\2\0\14\14\1\50\14\14\12\0"+
    "\1\14\2\0\12\14\1\51\4\14\1\52\11\14\12\0"+
    "\1\14\2\0\10\14\1\53\20\14\12\0\1\14\2\0"+
    "\7\14\1\54\21\14\12\0\1\14\2\0\21\14\1\55"+
    "\2\14\1\56\4\14\12\0\1\14\2\0\7\14\1\57"+
    "\21\14\12\0\1\14\2\0\23\14\1\60\2\14\1\61"+
    "\2\14\12\0\1\14\2\0\11\14\1\62\7\14\1\63"+
    "\7\14\12\0\1\14\2\0\17\14\1\64\11\14\12\0"+
    "\1\14\2\0\11\14\1\65\17\14\2\36\2\0\42\36"+
    "\12\0\1\66\45\0\1\14\2\0\5\14\1\67\23\14"+
    "\12\0\1\14\2\0\16\14\1\70\12\14\12\0\1\14"+
    "\2\0\7\14\1\71\21\14\12\0\1\14\2\0\22\14"+
    "\1\72\1\73\5\14\12\0\1\14\2\0\3\14\1\74"+
    "\25\14\12\0\1\14\2\0\16\14\1\75\12\14\12\0"+
    "\1\14\2\0\10\14\1\76\20\14\12\0\1\14\2\0"+
    "\22\14\1\77\6\14\12\0\1\14\2\0\16\14\1\100"+
    "\12\14\12\0\1\14\2\0\21\14\1\101\7\14\12\0"+
    "\1\14\2\0\26\14\1\102\2\14\12\0\1\14\2\0"+
    "\12\14\1\103\4\14\1\104\11\14\12\0\1\14\2\0"+
    "\4\14\1\105\24\14\12\0\1\14\2\0\23\14\1\106"+
    "\5\14\12\0\1\14\2\0\3\14\1\107\25\14\12\0"+
    "\1\14\2\0\12\14\1\110\16\14\12\0\1\14\2\0"+
    "\21\14\1\111\7\14\12\0\1\14\2\0\30\14\1\112"+
    "\12\0\1\14\2\0\12\14\1\113\16\14\12\0\1\14"+
    "\2\0\12\14\1\114\16\14\12\0\1\14\2\0\7\14"+
    "\1\115\21\14\12\0\1\14\2\0\23\14\1\116\5\14"+
    "\12\0\1\14\2\0\3\14\1\117\25\14\12\0\1\14"+
    "\2\0\7\14\1\120\21\14\12\0\1\14\2\0\5\14"+
    "\1\121\23\14\12\0\1\14\2\0\22\14\1\122\6\14"+
    "\12\0\1\14\2\0\23\14\1\123\5\14\12\0\1\14"+
    "\2\0\3\14\1\124\25\14\12\0\1\14\2\0\7\14"+
    "\1\125\21\14\12\0\1\14\2\0\3\14\1\126\25\14"+
    "\12\0\1\14\2\0\25\14\1\127\3\14\12\0\1\14"+
    "\2\0\23\14\1\130\5\14\12\0\1\14\2\0\14\14"+
    "\1\131\14\14\12\0\1\14\2\0\24\14\1\132\4\14"+
    "\12\0\1\14\2\0\23\14\1\133\5\14\12\0\1\14"+
    "\2\0\23\14\1\134\5\14\12\0\1\14\2\0\17\14"+
    "\1\135\11\14\12\0\1\14\2\0\6\14\1\136\22\14"+
    "\12\0\1\14\2\0\14\14\1\137\14\14\12\0\1\14"+
    "\2\0\20\14\1\140\10\14\12\0\1\14\2\0\12\14"+
    "\1\141\16\14\12\0\1\14\2\0\13\14\1\142\15\14"+
    "\12\0\1\14\2\0\11\14\1\143\17\14\12\0\1\14"+
    "\2\0\22\14\1\144\6\14\12\0\1\14\2\0\12\14"+
    "\1\145\16\14\12\0\1\14\2\0\24\14\1\146\4\14"+
    "\12\0\1\14\2\0\14\14\1\147\14\14\12\0\1\14"+
    "\2\0\3\14\1\150\25\14\12\0\1\14\2\0\7\14"+
    "\1\151\21\14\12\0\1\14\2\0\12\14\1\152\16\14"+
    "\12\0\1\14\2\0\21\14\1\153\7\14\12\0\1\14"+
    "\2\0\12\14\1\154\16\14\12\0\1\14\2\0\5\14"+
    "\1\155\23\14\12\0\1\14\2\0\26\14\1\156\2\14"+
    "\12\0\1\14\2\0\7\14\1\157\21\14\12\0\1\14"+
    "\2\0\23\14\1\160\5\14\12\0\1\14\2\0\15\14"+
    "\1\161\13\14\12\0\1\14\2\0\16\14\1\162\12\14"+
    "\12\0\1\14\2\0\14\14\1\163\14\14\12\0\1\14"+
    "\2\0\14\14\1\164\14\14\12\0\1\14\2\0\23\14"+
    "\1\165\5\14\12\0\1\14\2\0\5\14\1\166\23\14"+
    "\12\0\1\14\2\0\5\14\1\167\23\14\12\0\1\14"+
    "\2\0\16\14\1\170\12\14\12\0\1\14\2\0\5\14"+
    "\1\171\23\14\12\0\1\14\2\0\11\14\1\172\17\14"+
    "\12\0\1\14\2\0\12\14\1\173\16\14\12\0\1\14"+
    "\2\0\7\14\1\174\21\14\12\0\1\14\2\0\24\14"+
    "\1\175\4\14\12\0\1\14\2\0\23\14\1\176\5\14"+
    "\12\0\1\14\2\0\30\14\1\177\12\0\1\14\2\0"+
    "\7\14\1\200\21\14\12\0\1\14\2\0\23\14\1\201"+
    "\5\14\12\0\1\14\2\0\17\14\1\202\11\14\12\0"+
    "\1\14\2\0\1\14\1\203\27\14\12\0\1\14\2\0"+
    "\7\14\1\204\21\14\12\0\1\14\2\0\7\14\1\205"+
    "\21\14\12\0\1\14\2\0\16\14\1\206\12\14\12\0"+
    "\1\14\2\0\27\14\1\207\1\14\12\0\1\14\2\0"+
    "\6\14\1\210\22\14\12\0\1\14\2\0\5\14\1\211"+
    "\23\14\12\0\1\14\2\0\7\14\1\212\21\14\12\0"+
    "\1\14\2\0\20\14\1\213\10\14\12\0\1\14\2\0"+
    "\23\14\1\214\5\14\12\0\1\14\2\0\12\14\1\215"+
    "\16\14\12\0\1\14\2\0\17\14\1\216\11\14\12\0"+
    "\1\14\2\0\16\14\1\217\12\14";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4256];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\2\11\23\1\1\0"+
    "\1\11\1\1\1\0\160\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Caractere inválido: " + yytext());
            }
            // fall through
          case 36: break;
          case 2:
            { /* ignora espaços, tab, CR e newline */
            }
            // fall through
          case 37: break;
          case 3:
            { System.out.print(yytext());
            }
            // fall through
          case 38: break;
          case 4:
            { /* ignora delimitadores e espaços */
            }
            // fall through
          case 39: break;
          case 5:
            { System.out.println("TOKEN: OP " + yytext());
            }
            // fall through
          case 40: break;
          case 6:
            { System.out.println("TOKEN: INT " + yytext());
            }
            // fall through
          case 41: break;
          case 7:
            { System.out.println("TOKEN: ID " + yytext());
            }
            // fall through
          case 42: break;
          case 8:
            { System.out.println("TOKEN: STRING " + yytext());
            }
            // fall through
          case 43: break;
          case 9:
            { /* ignora comentários de linha */
            }
            // fall through
          case 44: break;
          case 10:
            { System.out.println("TOKEN: DO");
            }
            // fall through
          case 45: break;
          case 11:
            { System.out.println("TOKEN: IF");
            }
            // fall through
          case 46: break;
          case 12:
            { System.out.println("TOKEN: FLOAT " + yytext());
            }
            // fall through
          case 47: break;
          case 13:
            { System.out.println("TOKEN: FOR");
            }
            // fall through
          case 48: break;
          case 14:
            { System.out.println("TOKEN: NEW");
            }
            // fall through
          case 49: break;
          case 15:
            { System.out.println("TOKEN: TRY");
            }
            // fall through
          case 50: break;
          case 16:
            { System.out.println("TOKEN: CASE");
            }
            // fall through
          case 51: break;
          case 17:
            { System.out.println("TOKEN: ELSE");
            }
            // fall through
          case 52: break;
          case 18:
            { System.out.println("TOKEN: VOID");
            }
            // fall through
          case 53: break;
          case 19:
            { System.out.println("TOKEN: BREAK");
            }
            // fall through
          case 54: break;
          case 20:
            { System.out.println("TOKEN: CATCH");
            }
            // fall through
          case 55: break;
          case 21:
            { System.out.println("TOKEN: CLASS");
            }
            // fall through
          case 56: break;
          case 22:
            { System.out.println("TOKEN: FINAL");
            }
            // fall through
          case 57: break;
          case 23:
            { System.out.println("TOKEN: THROW");
            }
            // fall through
          case 58: break;
          case 24:
            { System.out.println("TOKEN: WHILE");
            }
            // fall through
          case 59: break;
          case 25:
            { System.out.println("TOKEN: PUBLIC");
            }
            // fall through
          case 60: break;
          case 26:
            { System.out.println("TOKEN: RETURN");
            }
            // fall through
          case 61: break;
          case 27:
            { System.out.println("TOKEN: STATIC");
            }
            // fall through
          case 62: break;
          case 28:
            { System.out.println("TOKEN: SWITCH");
            }
            // fall through
          case 63: break;
          case 29:
            { System.out.println("TOKEN: DEFAULT");
            }
            // fall through
          case 64: break;
          case 30:
            { System.out.println("TOKEN: FINALLY");
            }
            // fall through
          case 65: break;
          case 31:
            { System.out.println("TOKEN: PRIVATE");
            }
            // fall through
          case 66: break;
          case 32:
            { System.out.println("TOKEN: CONTINUE");
            }
            // fall through
          case 67: break;
          case 33:
            { System.out.println("TOKEN: EXCEPTION");
            }
            // fall through
          case 68: break;
          case 34:
            { System.out.println("TOKEN: PROTECTED");
            }
            // fall through
          case 69: break;
          case 35:
            { System.out.println("TOKEN: RUNTIME_EXCEPTION");
            }
            // fall through
          case 70: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
